### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-events-crash-course-lab#1]
The link in this sentence: "Have fun with an absolute legend" [legend is a link]
takes me here: https://en.wikipedia.org/wiki/Draft:Chrome_Boi
which gives me this error: Wikipedia does not have a Draft page with this exact name.

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for providing this feedback. It looks like @geluso replaced this link with an updated wiki page that includes the origin of ChromeBoi. We're also setting up to take ChromeBoi out of this lab in an upcoming version of our React materials and replace it with something simpler and more relevant
