### ISSUE TITLE
Tests do not pass with keycode, only passes with key

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/react-events-crash-course-lab#18]
Using keyCode to check which key was pressed fails 

`handleKeyPress = e => {
    if (e.keyCode === 65 ) {
      resize("+")
    } else if (e.keyCode === 83) {
      resize("-")
    }
  }`

**Comment by graciemcguire** [comment]
Hey @IgoVeyner, we only wrote these tests for
