### ISSUE TITLE
No visible results

### ISSUE THREAD

**Issue by drewkeat** [learn-co-curriculum/react-events-crash-course-lab#31]
### Canvas Link

https://learning.flatironschool.com/courses/1883/assignments/125693?module_item_id=259615

### Concern

I'm unsure of the issue, but after completing all of the tests for this lab, I see no visible results.  Based on the code, I would assume that an image will be stamped onto the canvas in cyclical RGB patterns.  However, after executing my event handlers properly enough to pass tests, I see nothing on the final page...

**Comment by lizbur10** [comment]
Hi @drewkeat ! I was not able to reproduce this issue - I pulled down your solution code for the lab and it behaved as expected in the browser for me. You might want to try it again.

If it's still not working for you, you should either: 

- Reach out to your instructor, or
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Hope you are able to get this resolved!
